function fig10(prn)

%% Local Variables
% Impostazione Figura
nx = 1;			% Numero di figure in orizzontale
ny = 2;			% Numero di figure in verticale
bx = 0.48*1.35; % Margini sinistro  e destro    [cm]
by = 0.30;		% Margini superiore e inferiore [cm]
fx = 7.5;		% Larghezza primo riquadro interno [cm]
fy = 1.6;		% Altezza riquadri interni   [cm]
dx = 0.0;		% Distanza orizzontale tra i riquadri [cm]
dy = 0.30;		% Distanza verticale tra i riquadri   [cm]
ox = 0.30;		% Offset orizzontale [cm]
oy = 0.03;		% Offset verticale   [cm]
ospl = 0.0;
fnt  = 8;		% Dimensione dei font per gli assi
fnl  = 8;		% Dimensione dei font per le labels
fnl2 = 7;		% Dimensione dei font per le labels

fwidth  = nx*fx+(nx-1)*dx+2*bx;
fheigth = ny*fy+(ny-1)*dy+2*by+ospl;
%%
lincol5=[0 0 0];            
lincol3=0.7*[1 1 1];      
lincol7=0.4*[1 1 1];       
lincol8=0.25*[1 1 1];
linwid1=0.5;              
linwid2=1.25;              
linwid0=0.25;
red = [204 37 41]./255;

colors = [lincol5; red; lincol3; lincol7];

%% Creazione Figura
figure('Renderer', 'Painters',...
    'units','centimeters',...
    'position',[bx, by, fwidth, fheigth], ...
    'PaperUnits','centimeters', ...
    'PaperOrientation','portrait', ...
    'PaperPosition',[bx, by, fwidth, fheigth], ...
    'PaperType','A4', ...
    'Color','white' ...
    );
%%
% Creazione Riquadri e Grafici
% #format table ## [WaveView Analyzer] saved 16:33:34 Sun Mar 17 2019

DEC     = 1;

load('dcInfAc_unbalanced.mat');

idx1 = find(time >= 1,1);
idx2 = find(time >= 1.2,1);


%%


for i=1:nx
    for j=1:ny
        h(i,j)=axes(...
            'units','centimeters',...
            'position',[bx+(i-1)*(fx+dx)+ox, by+(ny-j)*(fy+dy)+oy, fx fy],...
            'fontsize',fnt,...
            'fontname','helvetica',...
            'fontangle','normal',...
            'visible','on', ...
            'Color','none', ...
            'box','on', ...
            'XTickLabel', [], ...
            'YTickLabel', [], ...
            'XTick', [], ...
            'Ytick', []);
        
        OFF = 0;
        
        if j==1
            line(time, Va, 'Color', lincol5, ...
                'LineWidth',  linwid1,...
                'Linestyle','-');
            
            hold on
            
            line(time, Vb, 'Color', lincol7, ...
                'LineWidth',  linwid1,...
                'Linestyle','-');
            
            
            line(time, Vc, 'Color', lincol3, ...
                'LineWidth',  linwid1,...
                'Linestyle','-');
            
            
            xlim([time(idx1) time(idx2)])
            ylim([-135e3 190e3])
        end
        
        axis xy;
        grid on;
        hold on;
        
        set(h(i,j),...
            'units','centimeters',...
            'position',[bx+(i-1)*(fx+dx)+ox, by+(ny-j)*(fy+dy)+oy, fx fy],...
            'fontsize',fnt,...
            'fontname','helvetica',...
            'fontangle','normal',...
            'visible','on', ...
            'Color','none', ...
            'Xcolor',lincol7, ...
            'Ycolor',lincol7, ...
            'XTickMode', 'manual', ...
            'Xtick',[],...
            'YTickMode', 'manual', ...
            'Ytick',[], ...
            'box','on',...
            'Xscale','linear');
        
        if j==2
            
            line(time, Ia, 'Color', lincol5, ...
                'LineWidth',  linwid1,...
                'Linestyle','-');
            
            hold on
            
            line(time, Ib, 'Color', lincol7, ...
                'LineWidth',  linwid1,...
                'Linestyle','-');
            
            
            line(time, Ic, 'Color', lincol3, ...
                'LineWidth',  linwid1,...
                'Linestyle','-');

            xlim([time(idx1) time(idx2)])
            ylim([-3.5e3 5.3e3])
         
        end
        
        axis xy;
        grid on;
        hold on;
        
        set(h(i,j),...
            'units','centimeters',...
            'position',[bx+(i-1)*(fx+dx)+ox, by+(ny-j)*(fy+dy)+oy, fx fy],...
            'fontsize',fnt,...
            'fontname','helvetica',...
            'fontangle','normal',...
            'visible','on', ...
            'Color','none', ...
            'Xcolor',lincol7, ...
            'Ycolor',lincol7, ...
            'XTickMode', 'manual', ...
            'Xtick',[],...
            'YTickMode', 'manual', ...
            'Ytick',[], ...
            'box','on',...
            'Xscale','linear');
        
        if j==1
            format_ticks(h(i,j),{'$ $','$ $','$ $','$ $','$ $'},...
                {'$-130$','$-50$','$30$','$110$','$190$'},...
                (linspace(1,1.2,5)), (linspace(-130e3,190e3,5)),...
                [],[],[0.020 0.020]);
            axlbl={'$$ $$','$$ v_{\mathrm{AC1}} [\mathrm{kV}] $$'};
            
            lt=[0.98, 0.003];
            text(lt(1),lt(2),axlbl{1}, ...
                'fontname','times',...
                'fontangle','italic',...
                'fontsize',fnl, ...
                'fontweight', 'normal', ...
                'interpreter','latex',...
                'HorizontalAlignment','right',...
                'VerticalAlignment','bottom', ...
                'Color', 'black', ...
                'Unit', 'normalized' ...
                );
            
            lt=[0.02, 0.76];
            text(lt(1),lt(2),axlbl{2}, ...
                'fontname','times',...
                'fontangle','italic',...
                'fontsize',fnl, ...
                'fontweight', 'normal', ...
                'interpreter','latex',...
                'HorizontalAlignment','l',...
                'VerticalAlignment','bottom', ...
                'Unit', 'normalized' ...
                );
        end
        
        
        if j==2
            format_ticks(h(i,j),{'$1$','$1.05$','$1.10$','$1.15$','$1.2$'},...
                {'$-3.5$','$-1.3$' '$0.9$','$3.1$','$5.3$'},...
                (linspace(1,1.2,5)), (linspace(-3.5e3,5.4e3,5)),...
                [],[],[0.020 0.020]);
            axlbl={'$$t [s]$$','$$ i_{\mathrm{AC1}} [\mathrm{kA}] $$'};
            
            lt=[0.99, -0.7e-2];
            text(lt(1),lt(2),axlbl{1}, ...
                'fontname','times',...
                'fontangle','italic',...
                'fontsize',fnl, ...
                'fontweight', 'normal', ...
                'interpreter','latex',...
                'HorizontalAlignment','right',...
                'VerticalAlignment','bottom', ...
                'Color', 'black', ...
                'Unit', 'normalized' ...
                );
            
            lt=[0.02, 0.76];
            text(lt(1),lt(2),axlbl{2}, ...
                'fontname','times',...
                'fontangle','italic',...
                'fontsize',fnl, ...
                'fontweight', 'normal', ...
                'interpreter','latex',...
                'HorizontalAlignment','l',...
                'VerticalAlignment','bottom', ...
                'Unit', 'normalized' ...
                );
        end
    end
end


if(prn)
    print -loose -painters -depsc2 ..\figs\fig10.eps
end
