function fig6(prn)

%% Local Variables
% Impostazione Figura
nx = 1;			% Numero di figure in orizzontale
ny = 1;			% Numero di figure in verticale
bx = 0.48*1.15;	% Margini sinistro  e destro    [cm]
by = 0.30;		% Margini superiore e inferiore [cm]
fx = 7.5;	    % Larghezza primo riquadro interno [cm]
fy = 1.6;		% Altezza riquadri interni   [cm]
dx = 0.0;		% Distanza orizzontale tra i riquadri [cm]
dy = 0.32;		% Distanza verticale tra i riquadri   [cm]
ox = 0.30;		% Offset orizzontale [cm]
oy = 0.03;		% Offset verticale   [cm]
ospl = 0.0;
fnt  = 8;		% Dimensione dei font per gli assi
fnl  = 8;		% Dimensione dei font per le labels
fnl2 = 7;		% Dimensione dei font per le labels

fwidth  = nx*fx+(nx-1)*dx+2*bx;
fheigth = ny*fy+(ny-1)*dy+2*by+ospl;
%%
lincol1 = 'b';
lincol2 = [50 205 50]/256;
lincol3 = 'c';
lincol7 = 'm';
lincol5=[0 0 0];            
lincol2=0.66*[1 1 1];        
linwid1=0.75;             
linwid2=1.55;             
linwid0=1.5;

%% Creazione Figura
figure('Renderer', 'Painters',...
    'units','centimeters',...
    'position',[bx, by, fwidth, fheigth], ...
    'PaperUnits','centimeters', ...
    'PaperOrientation','portrait', ...
    'PaperPosition',[bx, by, fwidth, fheigth], ...
    'PaperType','A4', ...
    'Color','white' ...
    );
%%
% Creazione Riquadri e Grafici
% #format table ## [WaveView Analyzer] saved 16:33:34 Sun Mar 17 2019

load('Dcs1_800M.mat'); 

Ypp_freq = freq.';
Ypp  = -Ypp_0.' ;
Ypp_w =   2*pi*Ypp_freq;
EQUAL_WEIGHT = 1;
Npoles = 10;                                                               
Niter  = 100;
Ka   = 2;                                                                   % 1.-Strictly proper, 2.-Proper, 3.-Improper

if EQUAL_WEIGHT                                                             %Vector of 1 is used as custom_weights
    weight = ones(size(Ypp_freq));
else                                                                        %Previously computed custom_weights are loaded
    weight = 1./(abs(Ypp));
end

[Poles,Residues,Constant,Proportional] = ...
    fitting(Ypp,Ypp_freq,Npoles,Niter,Ka,weight);

Ypp_fit             = sum(Residues./(1i*Ypp_w - Poles)) + ...
    Constant + Proportional*1i*Ypp_w;

min([real(Ypp) imag(Ypp)])
max([real(Ypp) imag(Ypp)])

%%


for i=1:nx
    for j=1:ny
        h(i,j)=axes(...
            'units','centimeters',...
            'position',[bx+(i-1)*(fx+dx)+ox, by+(ny-j)*(fy+dy)+oy, fx fy],...
            'fontsize',fnt,...
            'fontname','helvetica',...
            'fontangle','normal',...
            'visible','on', ...
            'Color','none', ...
            'box','on', ...
            'XTickLabel', [], ...
            'YTickLabel', [], ...
            'XTick', [], ...
            'Ytick', []);
        
        OFF = 0;
        
        
        if j==1
            line(Ypp_freq, real(Ypp), 'Color', lincol5, ...
                'LineWidth',  linwid2,...
                'Linestyle','-');
            
            hold on
            
            line(Ypp_freq, imag(Ypp), 'Color', 'r', ...
                'LineWidth',  linwid2,...
                'Linestyle','-');
            
            line(Ypp_freq, real(Ypp_fit), 'Color', lincol2, ...
                'LineWidth',  linwid2,...
                'Linestyle','-.');

            line(Ypp_freq, imag(Ypp_fit), 'Color','b', ...
                'LineWidth',  linwid2,...
                'Linestyle','-.');
            
                grid on;
            
            axis([0 350 -0.02 0.09])
        end
        

        
        if j==1
            format_ticks(h(i,j),{'$0$','$50$','$100$','$150$','$200$','$250$','$300$','$350$'},...
                {'$-0.02$','$ $','$0.02$','$ $','$0.06$','$ $'},...
                ([0:50:350]), ([-0.02:0.02:0.08]),...
                [],[],[0.020 0.020]);
            axlbl={'$$ f [\mathrm{Hz}] $$','$$\mathrm{Re},\mathrm{Im} \{ Y_\mathrm{pp}^{(0)} \} [\mathrm{S}]$$'};
            
            lt=[0.90, 0.11];
            text(lt(1),lt(2),axlbl{1}, ...
                'fontname','times',...
                'fontangle','italic',...
                'fontsize',fnl, ...
                'fontweight', 'normal', ...
                'interpreter','latex',...
                'HorizontalAlignment','l',...
                'VerticalAlignment','bottom', ...
                'Unit', 'normalized' ...
                );
            
            lt=[0.05, 0.75];
            text(lt(1),lt(2),axlbl{2}, ...
                'fontname','times',...
                'fontangle','italic',...
                'fontsize',fnl, ...
                'fontweight', 'normal', ...
                'interpreter','latex',...
                'HorizontalAlignment','l',...
                'VerticalAlignment','bottom', ...
                'Unit', 'normalized' ...
                );
        end
        
    end
end

    if(prn)
        print -loose -painters -depsc2 fig6.eps
    end
