function fig8(prn)

%% Local Variables
% Impostazione Figura
nx = 1;			% Numero di figure in orizzontale
ny = 2;			% Numero di figure in verticale
bx = 0.48*1.35;	% Margini sinistro  e destro    [cm]
by = 0.30;		% Margini superiore e inferiore [cm]
fx = 7.5;		% Larghezza primo riquadro interno [cm]
fy = 2;		    % Altezza riquadri interni   [cm]
dx = 0.0;		% Distanza orizzontale tra i riquadri [cm]
dy = 0.20;		% Distanza verticale tra i riquadri   [cm]
ox = 0.30;		% Offset orizzontale [cm]
oy = 0.03;		% Offset verticale   [cm]
ospl = 0.0;
fnt  = 8;		% Dimensione dei font per gli assi
fnl  = 8;		% Dimensione dei font per le labels
fnl2 = 7;		% Dimensione dei font per le labels

fwidth  = nx*fx+(nx-1)*dx+2*bx;
fheigth = ny*fy+(ny-1)*dy+2*by+ospl;
%%
lincol5=[0 0 0];            % black
lincol3=0.7*[1 1 1];       % gray
lincol7=0.4*[1 1 1];        % gray
lincol8=0.25*[1 1 1];
linwid1=0.5;              % spessore 1
linwid2=1.25;              % spessore 2
linwid0=0.25;
red = [204 37 41]./255;


colors = [lincol5; red; lincol3; lincol7];

%% Creazione Figura
figure('Renderer', 'Painters',...
    'units','centimeters',...
    'position',[bx, by, fwidth, fheigth], ...
    'PaperUnits','centimeters', ...
    'PaperOrientation','portrait', ...
    'PaperPosition',[bx, by, fwidth, fheigth], ...
    'PaperType','A4', ...
    'Color','white' ...
    );
%%
% Creazione Riquadri e Grafici
% #format table ## [WaveView Analyzer] saved 16:33:34 Sun Mar 17 2019
% 
DEC     = 1;

tr = {'tr_50m.mat', 'tr_75m.mat', 'tr_100m.mat', 'tr_125m.mat'};

for p = 1:length(tr)
load(tr{p})
vdc_M1(p,:)  = VDC1(1:DEC:end);
pM1_ref(p,:) = -pref(1:DEC:end)*1e9;
pM1(p,:)     = -PM1(1:DEC:end);
end

%%


for i=1:nx
    for j=1:ny
        h(i,j)=axes(...
            'units','centimeters',...
            'position',[bx+(i-1)*(fx+dx)+ox, by+(ny-j)*(fy+dy)+oy, fx fy],...
            'fontsize',fnt,...
            'fontname','helvetica',...
            'fontangle','normal',...
            'visible','on', ...
            'Color','none', ...
            'box','on', ...
            'XTickLabel', [], ...
            'YTickLabel', [], ...
            'XTick', [], ...
            'Ytick', []);
        
        OFF = 0;
        
        if j==1
            for p = length(tr):-1:1
            line(time, vdc_M1(p,:), 'Color', colors(p,:), ...
                'LineWidth',  linwid1,...
                'Linestyle','-');
            
            hold on
            
            end
            
            
            xlim([0 time(end)])
            ylim([186e3 210e3])
        end
        
        axis xy;
        grid on;
        hold on;
        
        set(h(i,j),...
            'units','centimeters',...
            'position',[bx+(i-1)*(fx+dx)+ox, by+(ny-j)*(fy+dy)+oy, fx fy],...
            'fontsize',fnt,...
            'fontname','helvetica',...
            'fontangle','normal',...
            'visible','on', ...
            'Color','none', ...
            'Xcolor',lincol7, ...
            'Ycolor',lincol7, ...
            'XTickMode', 'manual', ...
            'Xtick',[],...
            'YTickMode', 'manual', ...
            'Ytick',[], ...
            'box','on',...
            'Xscale','linear');
        
        if j==2
            
            for p = length(tr):-1:1
            line(time, pM1(p,:), 'Color', colors(p,:), ...
                'LineWidth',  linwid1,...
                'Linestyle','-');
            
            hold on
            
            end

            
            xlim([0 time(end)])
            ylim([-5e8 5e8])

        end
        
        axis xy;
        grid on;
        hold on;
        
        set(h(i,j),...
            'units','centimeters',...
            'position',[bx+(i-1)*(fx+dx)+ox, by+(ny-j)*(fy+dy)+oy, fx fy],...
            'fontsize',fnt,...
            'fontname','helvetica',...
            'fontangle','normal',...
            'visible','on', ...
            'Color','none', ...
            'Xcolor',lincol7, ...
            'Ycolor',lincol7, ...
            'XTickMode', 'manual', ...
            'Xtick',[],...
            'YTickMode', 'manual', ...
            'Ytick',[], ...
            'box','on',...
            'Xscale','linear');
        
        if j==1
            format_ticks(h(i,j),{'$ $','$ $','$ $','$ $','$ $','$ $',...
                '$ $','$ $'},...
                {'$186$','$192$','$198$','$204$','$210$'},...
                ([0:6:42]), (linspace(186e3,210e3,5)),...
                [],[],[0.020 0.020]);
            axlbl={'$$ $$','$$ v_{\mathrm{dc1}} [\mathrm{kV}] $$'};
            
            lt=[0.98, 0.003];
            text(lt(1),lt(2),axlbl{1}, ...
                'fontname','times',...
                'fontangle','italic',...
                'fontsize',fnl, ...
                'fontweight', 'normal', ...
                'interpreter','latex',...
                'HorizontalAlignment','right',...
                'VerticalAlignment','bottom', ...
                'Color', 'black', ...
                'Unit', 'normalized' ...
                );
            
            lt=[0.02, 0.72];
            text(lt(1),lt(2),axlbl{2}, ...
                'fontname','times',...
                'fontangle','italic',...
                'fontsize',fnl, ...
                'fontweight', 'normal', ...
                'interpreter','latex',...
                'HorizontalAlignment','l',...
                'VerticalAlignment','bottom', ...
                'Unit', 'normalized' ...
                );
        end
        
        
        if j==2
             format_ticks(h(i,j),{'$0$','$6$','$12$','$18$','$24$','$30$',...
                '$36$','$42$'},...
             {'$-1.2$','$ $' '$-0.8$','$ $','$-0.4$','$ $','$0$', '$ $'},...
             ([0:6:42]), ([-1200e6 -1000e6 -800e6 -600e6 -400e6 -200e6 0 200e6]),...
             [],[],[0.020 0.020]);
             axlbl={'$$t [s]$$','$$ p_{\mathrm{MMC_1}} [\mathrm{GW}] $$'};
            
            lt=[0.99, -0.7e-2];
            text(lt(1),lt(2),axlbl{1}, ...
                'fontname','times',...
                'fontangle','italic',...
                'fontsize',fnl, ...
                'fontweight', 'normal', ...
                'interpreter','latex',...
                'HorizontalAlignment','right',...
                'VerticalAlignment','bottom', ...
                'Color', 'black', ...
                'Unit', 'normalized' ...
                );
            
            lt=[0.02, 0.72];
            text(lt(1),lt(2),axlbl{2}, ...
                'fontname','times',...
                'fontangle','italic',...
                'fontsize',fnl, ...
                'fontweight', 'normal', ...
                'interpreter','latex',...
                'HorizontalAlignment','l',...
                'VerticalAlignment','bottom', ...
                'Unit', 'normalized' ...
                );
        end
    end
end

    
    if(prn)
        print -loose -painters -depsc2 ..\figs\fig9.eps
    end
